# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1N3JUz1R2vGUTnOb_JE4sqf52NGsiJ6Ae
"""
# !pip install xgboost

import xgboost as xgb
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import LabelEncoder

# 데이터 로드 (예: iris 데이터셋)
iris = datasets.load_iris()
X = iris.data
y = iris.target

# 데이터셋 분리
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# 레이블 인코딩 (XGBoost는 레이블이 정수형이어야 합니다)
label_encoder = LabelEncoder()
y_train_encoded = label_encoder.fit_transform(y_train)
y_test_encoded = label_encoder.transform(y_test)

# XGBClassifier 모델 생성 및 학습
model = xgb.XGBClassifier(objective='multi:softmax', num_class=len(set(y_train_encoded)))
model.fit(X_train, y_train_encoded)

# 예측
y_pred = model.predict(X_test)

# 평가
accuracy = accuracy_score(y_test_encoded, y_pred)
print(f"Accuracy: {accuracy:.2f}")

