# -*- coding: utf-8 -*-
"""xboost_boston.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DJiL1yOtZZp-uTGwadJX5h97dHI6FcWp
"""

import xgboost as xgb
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
import numpy as np

# Boston Housing Dataset을 fetch_openml을 통해 불러오기
X, y = datasets.fetch_openml('boston', version=1, return_X_y=True, as_frame=True)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# 카테고리 변수를 수치형으로 변환
X_train['CHAS'] = X_train['CHAS'].cat.codes
X_train['RAD'] = X_train['RAD'].cat.codes
X_test['CHAS'] = X_test['CHAS'].cat.codes
X_test['RAD'] = X_test['RAD'].cat.codes

# XGBoost 모델 설정
model = xgb.XGBRegressor(objective ='reg:squarederror', colsample_bytree = 0.3, learning_rate = 0.1,
                max_depth = 5, alpha = 10, n_estimators = 100)

# 모델 학습
model.fit(X_train, y_train)

# 예측
y_pred = model.predict(X_test)

# 평가
rmse = np.sqrt(mean_squared_error(y_test, y_pred))
print("RMSE: %f" % (rmse))



